### ISSUE TITLE
test for orphans having precedent

### ISSUE THREAD

**Issue by fommil** [fommil/stalactite#10]
I have some evidence that orphan instances are being ignored in favour of the stalactite derived version.

Let's get a test added and investigate.

**Comment by fommil** [comment]
(I think this is actually the correct behaviour, but it is against what the scala implicit resolution spec says and is a regression vs full generic derivation)

**Comment by pjrt** [comment]
In Haskell, the idea is that if you want an orphan, then what you REALLY want is a newtype (aka, not an orphan). Sadly, Scala's support for newtypes is lacking. 

We can try to derive `AnyVal` but even then, due to AnyVal's not really being newtype, some ppl might want to avoid it.

**Comment by fommil** [comment]
`AnyVal` you say? #9 :wink:
