### ISSUE TITLE
better errors

### ISSUE THREAD

**Issue by fommil** [fommil/stalactite#11]
this could be a single compiler error and not a stack trace

```
exception during macro expansion: 
[error] scala.reflect.macros.TypecheckException: not found: object Encoder
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:34)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
[error] 	at scala.reflect.macros.contexts.Typers$class.withContext$1(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
[error] 	at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1716)
[error] 	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
[error] 	at scala.reflect.macros.contexts.Typers$class.withWrapping$1(Typers.scala:26)
[error] 	at scala.reflect.macros.contexts.Typers$class.typecheck(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at stalactite.DerivingMacros.generateImplicits(deriving.scala:52)
[error] @deriving(Encoder, Decoder)
```

**Comment by fommil** [comment]
it's even worse than this if implicit derivation fails, we just get

`<macro>:1: thing` https://github.com/scalamacros/paradise/issues/104

**Comment by fommil** [comment]
@hrhino suggests doing the typechecking before returning https://gitter.im/scala/contributors?at=59a01bd966c1c7c477ddb234

giving us the ability to force errors within the macro. But I suspect this could interfere with generic derivation.

**Comment by fommil** [comment]
(Harrison also points out that the ValDef LHS has pos, but not the RHS. My suspect is quasiquotes)

**Comment by hrhino** [comment]
Your suspicion appears to be correct: all of the manual trees are unpositioned; all of the quasiquoted strings are positioned in "<macro>:whatever".

If you don't want to go dropping quasiquotes _everywhere_... this is hackish but works.

```scala
  def reposition[T <: Tree](pos: Position)(t: T): T = {
    val symtab =
      c.universe.asInstanceOf[_root_.scala.reflect.internal.SymbolTable]

    object Unposition extends Traverser {
      override def traverse(tree: c.universe.Tree): scala.Unit =
        if (tree.canHaveAttrs) {
          tree.asInstanceOf[symtab.Tree].setPos(symtab.NoPosition)
          super.traverse(tree)
        }
    }

    atPos(pos)(Unposition(t))
  }
```

**Comment by fommil** [comment]
yeah I think I had something similar in https://github.com/ensime/pcplod/blob/master/example/src/main/scala/org/ensime/noddy/NoddyPlugin.scala#L39-L47

**Comment by fommil** [comment]
@hrhino that's really great, and works! How are you working out the parts that have `<macro>` in the positions? If I do `showRaw(showPositions = true)` I don't see `<macro>` anywhere.

I would like to remove quasis everywhere but I can't work out how to remove the two uses that I currently have, I can't work out how to replace one use of `parse`, and there is one place where I'm just being straight up lazy (`toGen`).
