### ISSUE TITLE
pcplod tests are failing

### ISSUE THREAD

**Issue by fommil** [fommil/stalactite#12]
I think I need the help of @dragos or @xeno-by for this...

Turn `ignore` to `in` in the `PresentationCompilerTest.scala` and see that `type-at-point` fails when using this macro. Using `-Y:macro-expand:discard` entirely ignores the output of the macro.

I suspect I'm doing something silly with positions. An audit of the macro would be muchly appreciated.

**Comment by dragos** [comment]
Yes, you don't seem to set any positions in the trees you generate. Maybe you can assign tree.pos to the result?

**Comment by fommil** [comment]
I tried that in this branch https://github.com/fommil/stalactite/commits/feature/dev

But macro-paradise seems to throw them away :man_shrugging:
