### ISSUE TITLE
@deriving can't handle `private` classes

### ISSUE THREAD

**Issue by pjrt** [fommil/stalactite#19]
Version: 0.0.2

```scala
@deriving(Encoder)
private final case class SomeClass(x: Int)
```

This throws the following error:

```
private class SomeClass escapes its defining scope as part of type Encoder[SomeClass]
```
### Work around
Manually adding a `private object SomeClass` solves it.

**Comment by fommil** [comment]
interesting, I thought we preserved the mods

**Comment by pjrt** [comment]
https://github.com/fommil/stalactite/blob/f6f7ac97246da4a9a0d41eae831df7fe852fe4cc/src/main/scala/stalagtite/deriving.scala#L76

We do, for the companion object. However we need to capture the mods for the class itself too. 

Now sure how though. How would the following work?

```scala
@deriving(Something)
private final case class A(i: Int)
object A {
   // some public stuff
}
```

There the companion is public, but the type is private. We could just not allow that (I mean, how common is that?) with some error.

**Comment by fommil** [comment]
ok, this is where we break it https://github.com/fommil/stalactite/blob/master/src/main/scala/stalagtite/deriving.scala#L141

We need to include the visibility modifier of the `ClassDef`

**Comment by fommil** [comment]
incidentally this is where we're also breaking #18
